apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-quarkus
spec:
  selector:
    matchLabels:
      app: backend-quarkus
  replicas: 2
  template:
    metadata:
      labels:
        app: backend-quarkus
    spec:
      containers:
        - name: backend-quarkus
          image: nanagiannis/quarkus-backend-training-image:0.0.1
          ports:
          - containerPort: 8081